# Generated by Django 6.0.6 on 2026-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=100)),
                ('destination_ip', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=20)),
                ('packet_size', models.IntegerField()),
                ('anomaly_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
